// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKOndV4flug5y2Lp1vM4uSOpJ4fDTIkp8',
    appId: '1:283953571857:web:bcdb9a7928312df89529b0',
    messagingSenderId: '283953571857',
    projectId: 'e-commerce-4baed',
    authDomain: 'e-commerce-4baed.firebaseapp.com',
    storageBucket: 'e-commerce-4baed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZurKzrmFw1jj-8T1K3D6O8W8pT1AueII',
    appId: '1:283953571857:android:3212383d88a06c7b9529b0',
    messagingSenderId: '283953571857',
    projectId: 'e-commerce-4baed',
    storageBucket: 'e-commerce-4baed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdWX77cKDBLTUX8msitT40i5JQOKoEWlI',
    appId: '1:283953571857:ios:6d4796ca5f5b76f19529b0',
    messagingSenderId: '283953571857',
    projectId: 'e-commerce-4baed',
    storageBucket: 'e-commerce-4baed.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdWX77cKDBLTUX8msitT40i5JQOKoEWlI',
    appId: '1:283953571857:ios:6d4796ca5f5b76f19529b0',
    messagingSenderId: '283953571857',
    projectId: 'e-commerce-4baed',
    storageBucket: 'e-commerce-4baed.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKOndV4flug5y2Lp1vM4uSOpJ4fDTIkp8',
    appId: '1:283953571857:web:22ec9faf4bff3aef9529b0',
    messagingSenderId: '283953571857',
    projectId: 'e-commerce-4baed',
    authDomain: 'e-commerce-4baed.firebaseapp.com',
    storageBucket: 'e-commerce-4baed.firebasestorage.app',
  );
}
